// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: greeter/v1/greeter.proto

package greeter

import (
	v1 "github.com/origadmin/runtime/api/gen/go/config/middleware/cors/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_greeter_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_greeter_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_greeter_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_greeter_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExampleCors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cors          *v1.Cors               `protobuf:"bytes,1,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleCors) Reset() {
	*x = ExampleCors{}
	mi := &file_greeter_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleCors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleCors) ProtoMessage() {}

func (x *ExampleCors) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleCors.ProtoReflect.Descriptor instead.
func (*ExampleCors) Descriptor() ([]byte, []int) {
	return file_greeter_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleCors) GetCors() *v1.Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

var File_greeter_v1_greeter_proto protoreflect.FileDescriptor

const file_greeter_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x18greeter/v1/greeter.proto\x12\n" +
	"greeter.v1\x1a$config/middleware/cors/v1/cors.proto\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"N\n" +
	"\vExampleCors\x12?\n" +
	"\x04cors\x18\x01 \x01(\v2+.runtime.api.config.middleware.cors.v1.CorsR\x04cors2\x84\x01\n" +
	"\x0eGreeterService\x12r\n" +
	"\bSayHello\x12\x1b.greeter.v1.SayHelloRequest\x1a\x1c.greeter.v1.SayHelloResponse\"+\x82\xd3\xe4\x93\x02%Z\x0f:\x01*\"\n" +
	"/say_hello\x12\x12/helloworld/{name}B\xb4\x01\n" +
	"\x0ecom.greeter.v1B\fGreeterProtoP\x01ZKgithub.com/origadmin/contrib/examples/helloword/services/greeter/v1;greeter\xa2\x02\x03GXX\xaa\x02\n" +
	"Greeter.V1\xca\x02\n" +
	"Greeter\\V1\xe2\x02\x16Greeter\\V1\\GPBMetadata\xea\x02\vGreeter::V1b\x06proto3"

var (
	file_greeter_v1_greeter_proto_rawDescOnce sync.Once
	file_greeter_v1_greeter_proto_rawDescData []byte
)

func file_greeter_v1_greeter_proto_rawDescGZIP() []byte {
	file_greeter_v1_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_v1_greeter_proto_rawDesc), len(file_greeter_v1_greeter_proto_rawDesc)))
	})
	return file_greeter_v1_greeter_proto_rawDescData
}

var file_greeter_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_greeter_v1_greeter_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: greeter.v1.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: greeter.v1.SayHelloResponse
	(*ExampleCors)(nil),      // 2: greeter.v1.ExampleCors
	(*v1.Cors)(nil),          // 3: runtime.api.config.middleware.cors.v1.Cors
}
var file_greeter_v1_greeter_proto_depIdxs = []int32{
	3, // 0: greeter.v1.ExampleCors.cors:type_name -> runtime.api.config.middleware.cors.v1.Cors
	0, // 1: greeter.v1.GreeterService.SayHello:input_type -> greeter.v1.SayHelloRequest
	1, // 2: greeter.v1.GreeterService.SayHello:output_type -> greeter.v1.SayHelloResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_greeter_v1_greeter_proto_init() }
func file_greeter_v1_greeter_proto_init() {
	if File_greeter_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_v1_greeter_proto_rawDesc), len(file_greeter_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_v1_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_v1_greeter_proto_depIdxs,
		MessageInfos:      file_greeter_v1_greeter_proto_msgTypes,
	}.Build()
	File_greeter_v1_greeter_proto = out.File
	file_greeter_v1_greeter_proto_goTypes = nil
	file_greeter_v1_greeter_proto_depIdxs = nil
}
