// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from consul.go.

// Package consul contains generated code by adptool.
package consul

import (
	"context"

	consul "github.com/go-kratos/kratos/contrib/config/consul/v2"
	"github.com/go-kratos/kratos/v2/config"
	"github.com/hashicorp/consul/api"
)

type Option = consul.Option

func New(client *api.Client, opts ...consul.Option) (config.Source, error) {
	return consul.New(client, opts...)
}

func WithContext(ctx context.Context) consul.Option {
	return consul.WithContext(ctx)
}

func WithPath(p string) consul.Option {
	return consul.WithPath(p)
}
