// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from etcd.go.

// Package etcd contains generated code by adptool.
package etcd

import (
	"context"
	"time"

	etcd "github.com/go-kratos/kratos/contrib/registry/etcd/v2"
	clientv3 "go.etcd.io/etcd/client/v3"
)

type (
	Option   = etcd.Option
	Registry = etcd.Registry
)

func Context(ctx context.Context) etcd.Option {
	return etcd.Context(ctx)
}

func MaxRetry(num int) etcd.Option {
	return etcd.MaxRetry(num)
}

func Namespace(ns string) etcd.Option {
	return etcd.Namespace(ns)
}

func New(client *clientv3.Client, opts ...etcd.Option) (r *etcd.Registry) {
	return etcd.New(client, opts...)
}

func RegisterTTL(ttl time.Duration) etcd.Option {
	return etcd.RegisterTTL(ttl)
}
