// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from consul.go.

// Package consul contains generated code by adptool.
package consul

import (
	"crypto/tls"
	"net/http"
	"time"

	api "github.com/hashicorp/consul/api"
	"github.com/hashicorp/go-hclog"
)

const (
	ACLClientType                              = api.ACLClientType
	ACLManagementType                          = api.ACLManagementType
	ACLModeDisabled                            = api.ACLModeDisabled
	ACLModeEnabled                             = api.ACLModeEnabled
	ACLModeLegacy                              = api.ACLModeLegacy
	ACLModeUnknown                             = api.ACLModeUnknown
	ACLTemplatedPolicyAPIGatewayName           = api.ACLTemplatedPolicyAPIGatewayName
	ACLTemplatedPolicyDNSName                  = api.ACLTemplatedPolicyDNSName
	ACLTemplatedPolicyNodeName                 = api.ACLTemplatedPolicyNodeName
	ACLTemplatedPolicyNomadClientName          = api.ACLTemplatedPolicyNomadClientName
	ACLTemplatedPolicyNomadServerName          = api.ACLTemplatedPolicyNomadServerName
	ACLTemplatedPolicyServiceName              = api.ACLTemplatedPolicyServiceName
	APIGateway                                 = api.APIGateway
	AllSegments                                = api.AllSegments
	AutopilotServerLeader                      = api.AutopilotServerLeader
	AutopilotServerNonVoter                    = api.AutopilotServerNonVoter
	AutopilotServerNone                        = api.AutopilotServerNone
	AutopilotServerStaging                     = api.AutopilotServerStaging
	AutopilotServerVoter                       = api.AutopilotServerVoter
	AutopilotTypeReadReplica                   = api.AutopilotTypeReadReplica
	AutopilotTypeVoter                         = api.AutopilotTypeVoter
	AutopilotTypeZoneExtraVoter                = api.AutopilotTypeZoneExtraVoter
	AutopilotTypeZoneStandby                   = api.AutopilotTypeZoneStandby
	AutopilotTypeZoneVoter                     = api.AutopilotTypeZoneVoter
	AutopilotUpgradeAwaitNewServers            = api.AutopilotUpgradeAwaitNewServers
	AutopilotUpgradeAwaitNewVoters             = api.AutopilotUpgradeAwaitNewVoters
	AutopilotUpgradeAwaitServerRemoval         = api.AutopilotUpgradeAwaitServerRemoval
	AutopilotUpgradeDemoting                   = api.AutopilotUpgradeDemoting
	AutopilotUpgradeDisabled                   = api.AutopilotUpgradeDisabled
	AutopilotUpgradeIdle                       = api.AutopilotUpgradeIdle
	AutopilotUpgradeLeaderTransfer             = api.AutopilotUpgradeLeaderTransfer
	AutopilotUpgradePromoting                  = api.AutopilotUpgradePromoting
	BindingRuleBindTypeNode                    = api.BindingRuleBindTypeNode
	BindingRuleBindTypePolicy                  = api.BindingRuleBindTypePolicy
	BindingRuleBindTypeRole                    = api.BindingRuleBindTypeRole
	BindingRuleBindTypeService                 = api.BindingRuleBindTypeService
	BindingRuleBindTypeTemplatedPolicy         = api.BindingRuleBindTypeTemplatedPolicy
	BuiltinAWSLambdaExtension                  = api.BuiltinAWSLambdaExtension
	BuiltinExtAuthzExtension                   = api.BuiltinExtAuthzExtension
	BuiltinLuaExtension                        = api.BuiltinLuaExtension
	BuiltinOTELAccessLoggingExtension          = api.BuiltinOTELAccessLoggingExtension
	BuiltinPropertyOverrideExtension           = api.BuiltinPropertyOverrideExtension
	BuiltinValidateExtension                   = api.BuiltinValidateExtension
	BuiltinWasmExtension                       = api.BuiltinWasmExtension
	CheckCAS                                   = api.CheckCAS
	CheckDelete                                = api.CheckDelete
	CheckDeleteCAS                             = api.CheckDeleteCAS
	CheckGet                                   = api.CheckGet
	CheckSet                                   = api.CheckSet
	ConditionStatusFalse                       = api.ConditionStatusFalse
	ConditionStatusTrue                        = api.ConditionStatusTrue
	ConditionStatusUnknown                     = api.ConditionStatusUnknown
	DefaultLockRetryTime                       = api.DefaultLockRetryTime
	DefaultLockSessionName                     = api.DefaultLockSessionName
	DefaultLockSessionTTL                      = api.DefaultLockSessionTTL
	DefaultLockWaitTime                        = api.DefaultLockWaitTime
	DefaultLogSinkType                         = api.DefaultLogSinkType
	DefaultMonitorRetryTime                    = api.DefaultMonitorRetryTime
	DefaultSemaphoreKey                        = api.DefaultSemaphoreKey
	DefaultSemaphoreSessionName                = api.DefaultSemaphoreSessionName
	DefaultSemaphoreSessionTTL                 = api.DefaultSemaphoreSessionTTL
	DefaultSemaphoreWaitTime                   = api.DefaultSemaphoreWaitTime
	DiscoveryGraphNodeTypeResolver             = api.DiscoveryGraphNodeTypeResolver
	DiscoveryGraphNodeTypeRouter               = api.DiscoveryGraphNodeTypeRouter
	DiscoveryGraphNodeTypeSplitter             = api.DiscoveryGraphNodeTypeSplitter
	DiscoveryTypeEDS                           = api.DiscoveryTypeEDS
	DiscoveryTypeLogicalDNS                    = api.DiscoveryTypeLogicalDNS
	DiscoveryTypeOriginalDST                   = api.DiscoveryTypeOriginalDST
	DiscoveryTypeStatic                        = api.DiscoveryTypeStatic
	DiscoveryTypeStrictDNS                     = api.DiscoveryTypeStrictDNS
	ExportedServices                           = api.ExportedServices
	FileLogSinkType                            = api.FileLogSinkType
	FileSystemCertificate                      = api.FileSystemCertificate
	GRPCAddrEnvName                            = api.GRPCAddrEnvName
	GRPCCAFileEnvName                          = api.GRPCCAFileEnvName
	GRPCCAPathEnvName                          = api.GRPCCAPathEnvName
	GatewayConditionAccepted                   = api.GatewayConditionAccepted
	GatewayConditionConflicted                 = api.GatewayConditionConflicted
	GatewayConditionResolvedRefs               = api.GatewayConditionResolvedRefs
	GatewayListenerReasonInvalidCertificateRef = api.GatewayListenerReasonInvalidCertificateRef
	GatewayListenerReasonInvalidJWTProviderRef = api.GatewayListenerReasonInvalidJWTProviderRef
	GatewayReasonAccepted                      = api.GatewayReasonAccepted
	GatewayReasonInvalidCertificates           = api.GatewayReasonInvalidCertificates
	GatewayReasonInvalidJWTProviders           = api.GatewayReasonInvalidJWTProviders
	GatewayReasonNoConflict                    = api.GatewayReasonNoConflict
	GatewayReasonResolvedRefs                  = api.GatewayReasonResolvedRefs
	GatewayReasonRouteConflict                 = api.GatewayReasonRouteConflict
	HTTPAddrEnvName                            = api.HTTPAddrEnvName
	HTTPAuthEnvName                            = api.HTTPAuthEnvName
	HTTPCAFile                                 = api.HTTPCAFile
	HTTPCAPath                                 = api.HTTPCAPath
	HTTPClientCert                             = api.HTTPClientCert
	HTTPClientKey                              = api.HTTPClientKey
	HTTPHeaderMatchExact                       = api.HTTPHeaderMatchExact
	HTTPHeaderMatchPrefix                      = api.HTTPHeaderMatchPrefix
	HTTPHeaderMatchPresent                     = api.HTTPHeaderMatchPresent
	HTTPHeaderMatchRegularExpression           = api.HTTPHeaderMatchRegularExpression
	HTTPHeaderMatchSuffix                      = api.HTTPHeaderMatchSuffix
	HTTPMatchMethodAll                         = api.HTTPMatchMethodAll
	HTTPMatchMethodConnect                     = api.HTTPMatchMethodConnect
	HTTPMatchMethodDelete                      = api.HTTPMatchMethodDelete
	HTTPMatchMethodGet                         = api.HTTPMatchMethodGet
	HTTPMatchMethodHead                        = api.HTTPMatchMethodHead
	HTTPMatchMethodOptions                     = api.HTTPMatchMethodOptions
	HTTPMatchMethodPatch                       = api.HTTPMatchMethodPatch
	HTTPMatchMethodPost                        = api.HTTPMatchMethodPost
	HTTPMatchMethodPut                         = api.HTTPMatchMethodPut
	HTTPMatchMethodTrace                       = api.HTTPMatchMethodTrace
	HTTPNamespaceEnvName                       = api.HTTPNamespaceEnvName
	HTTPPartitionEnvName                       = api.HTTPPartitionEnvName
	HTTPPathMatchExact                         = api.HTTPPathMatchExact
	HTTPPathMatchPrefix                        = api.HTTPPathMatchPrefix
	HTTPPathMatchRegularExpression             = api.HTTPPathMatchRegularExpression
	HTTPQueryMatchExact                        = api.HTTPQueryMatchExact
	HTTPQueryMatchPresent                      = api.HTTPQueryMatchPresent
	HTTPQueryMatchRegularExpression            = api.HTTPQueryMatchRegularExpression
	HTTPRoute                                  = api.HTTPRoute
	HTTPSSLEnvName                             = api.HTTPSSLEnvName
	HTTPSSLVerifyEnvName                       = api.HTTPSSLVerifyEnvName
	HTTPTLSServerName                          = api.HTTPTLSServerName
	HTTPTokenEnvName                           = api.HTTPTokenEnvName
	HTTPTokenFileEnvName                       = api.HTTPTokenFileEnvName
	HealthAny                                  = api.HealthAny
	HealthCritical                             = api.HealthCritical
	HealthMaint                                = api.HealthMaint
	HealthPassing                              = api.HealthPassing
	HealthWarning                              = api.HealthWarning
	IngressGateway                             = api.IngressGateway
	InlineCertificate                          = api.InlineCertificate
	IntentionActionAllow                       = api.IntentionActionAllow
	IntentionActionDeny                        = api.IntentionActionDeny
	IntentionDefaultNamespace                  = api.IntentionDefaultNamespace
	IntentionMatchDestination                  = api.IntentionMatchDestination
	IntentionMatchSource                       = api.IntentionMatchSource
	IntentionSourceConsul                      = api.IntentionSourceConsul
	JWTProvider                                = api.JWTProvider
	KVCAS                                      = api.KVCAS
	KVCheckIndex                               = api.KVCheckIndex
	KVCheckNotExists                           = api.KVCheckNotExists
	KVCheckSession                             = api.KVCheckSession
	KVDelete                                   = api.KVDelete
	KVDeleteCAS                                = api.KVDeleteCAS
	KVDeleteTree                               = api.KVDeleteTree
	KVGet                                      = api.KVGet
	KVGetOrEmpty                               = api.KVGetOrEmpty
	KVGetTree                                  = api.KVGetTree
	KVLock                                     = api.KVLock
	KVSet                                      = api.KVSet
	KVUnlock                                   = api.KVUnlock
	LockFlagValue                              = api.LockFlagValue
	MemberTagKeyACLMode                        = api.MemberTagKeyACLMode
	MemberTagKeyBootstrap                      = api.MemberTagKeyBootstrap
	MemberTagKeyBootstrapExpect                = api.MemberTagKeyBootstrapExpect
	MemberTagKeyDatacenter                     = api.MemberTagKeyDatacenter
	MemberTagKeyPartition                      = api.MemberTagKeyPartition
	MemberTagKeyReadReplica                    = api.MemberTagKeyReadReplica
	MemberTagKeyRole                           = api.MemberTagKeyRole
	MemberTagKeySegment                        = api.MemberTagKeySegment
	MemberTagKeyUseTLS                         = api.MemberTagKeyUseTLS
	MemberTagValueBootstrap                    = api.MemberTagValueBootstrap
	MemberTagValueReadReplica                  = api.MemberTagValueReadReplica
	MemberTagValueRoleClient                   = api.MemberTagValueRoleClient
	MemberTagValueRoleServer                   = api.MemberTagValueRoleServer
	MemberTagValueUseTLS                       = api.MemberTagValueUseTLS
	MeshConfig                                 = api.MeshConfig
	MeshConfigMesh                             = api.MeshConfigMesh
	MeshGatewayModeDefault                     = api.MeshGatewayModeDefault
	MeshGatewayModeLocal                       = api.MeshGatewayModeLocal
	MeshGatewayModeNone                        = api.MeshGatewayModeNone
	MeshGatewayModeRemote                      = api.MeshGatewayModeRemote
	MutualTLSModeDefault                       = api.MutualTLSModeDefault
	MutualTLSModePermissive                    = api.MutualTLSModePermissive
	MutualTLSModeStrict                        = api.MutualTLSModeStrict
	NodeCAS                                    = api.NodeCAS
	NodeDelete                                 = api.NodeDelete
	NodeDeleteCAS                              = api.NodeDeleteCAS
	NodeGet                                    = api.NodeGet
	NodeMaint                                  = api.NodeMaint
	NodeSet                                    = api.NodeSet
	PartitionDefaultName                       = api.PartitionDefaultName
	PeeringStateActive                         = api.PeeringStateActive
	PeeringStateDeleting                       = api.PeeringStateDeleting
	PeeringStateEstablishing                   = api.PeeringStateEstablishing
	PeeringStateFailing                        = api.PeeringStateFailing
	PeeringStatePending                        = api.PeeringStatePending
	PeeringStateTerminated                     = api.PeeringStateTerminated
	PeeringStateUndefined                      = api.PeeringStateUndefined
	ProxyConfigGlobal                          = api.ProxyConfigGlobal
	ProxyDefaults                              = api.ProxyDefaults
	ProxyModeDefault                           = api.ProxyModeDefault
	ProxyModeDirect                            = api.ProxyModeDirect
	ProxyModeTransparent                       = api.ProxyModeTransparent
	QueryBackendBlockingQuery                  = api.QueryBackendBlockingQuery
	QueryBackendStreaming                      = api.QueryBackendStreaming
	RateLimitIPConfig                          = api.RateLimitIPConfig
	RouteConditionAccepted                     = api.RouteConditionAccepted
	RouteConditionBound                        = api.RouteConditionBound
	RouteReasonAccepted                        = api.RouteReasonAccepted
	RouteReasonBound                           = api.RouteReasonBound
	RouteReasonFailedToBind                    = api.RouteReasonFailedToBind
	RouteReasonGatewayNotFound                 = api.RouteReasonGatewayNotFound
	RouteReasonInvalidDiscoveryChain           = api.RouteReasonInvalidDiscoveryChain
	RouteReasonJWTProvidersNotFound            = api.RouteReasonJWTProvidersNotFound
	RouteReasonNoUpstreamServicesTargeted      = api.RouteReasonNoUpstreamServicesTargeted
	SamenessGroup                              = api.SamenessGroup
	SemaphoreFlagValue                         = api.SemaphoreFlagValue
	ServiceCAS                                 = api.ServiceCAS
	ServiceDefaults                            = api.ServiceDefaults
	ServiceDelete                              = api.ServiceDelete
	ServiceDeleteCAS                           = api.ServiceDeleteCAS
	ServiceGet                                 = api.ServiceGet
	ServiceIntentions                          = api.ServiceIntentions
	ServiceKindAPIGateway                      = api.ServiceKindAPIGateway
	ServiceKindConnectProxy                    = api.ServiceKindConnectProxy
	ServiceKindIngressGateway                  = api.ServiceKindIngressGateway
	ServiceKindMeshGateway                     = api.ServiceKindMeshGateway
	ServiceKindTerminatingGateway              = api.ServiceKindTerminatingGateway
	ServiceKindTypical                         = api.ServiceKindTypical
	ServiceMaintPrefix                         = api.ServiceMaintPrefix
	ServiceResolver                            = api.ServiceResolver
	ServiceRouter                              = api.ServiceRouter
	ServiceSet                                 = api.ServiceSet
	ServiceSplitter                            = api.ServiceSplitter
	SessionBehaviorDelete                      = api.SessionBehaviorDelete
	SessionBehaviorRelease                     = api.SessionBehaviorRelease
	SessionDelete                              = api.SessionDelete
	StdErrLogSinkType                          = api.StdErrLogSinkType
	StdOutLogSinkType                          = api.StdOutLogSinkType
	TCPRoute                                   = api.TCPRoute
	TelemetryCollectorName                     = api.TelemetryCollectorName
	TerminatingGateway                         = api.TerminatingGateway
	UpstreamDestTypePreparedQuery              = api.UpstreamDestTypePreparedQuery
	UpstreamDestTypeService                    = api.UpstreamDestTypeService
)

var (
	ErrLockConflict      = api.ErrLockConflict
	ErrLockHeld          = api.ErrLockHeld
	ErrLockInUse         = api.ErrLockInUse
	ErrLockNotHeld       = api.ErrLockNotHeld
	ErrSemaphoreConflict = api.ErrSemaphoreConflict
	ErrSemaphoreHeld     = api.ErrSemaphoreHeld
	ErrSemaphoreInUse    = api.ErrSemaphoreInUse
	ErrSemaphoreNotHeld  = api.ErrSemaphoreNotHeld
	ErrSessionExpired    = api.ErrSessionExpired
)

type (
	ACL                                 = api.ACL
	ACLAuthMethod                       = api.ACLAuthMethod
	ACLAuthMethodListEntry              = api.ACLAuthMethodListEntry
	ACLAuthMethodNamespaceRule          = api.ACLAuthMethodNamespaceRule
	ACLBindingRule                      = api.ACLBindingRule
	ACLEntry                            = api.ACLEntry
	ACLLink                             = api.ACLLink
	ACLLoginParams                      = api.ACLLoginParams
	ACLNodeIdentity                     = api.ACLNodeIdentity
	ACLOIDCAuthURLParams                = api.ACLOIDCAuthURLParams
	ACLOIDCCallbackParams               = api.ACLOIDCCallbackParams
	ACLPolicy                           = api.ACLPolicy
	ACLPolicyListEntry                  = api.ACLPolicyListEntry
	ACLReplicationStatus                = api.ACLReplicationStatus
	ACLRole                             = api.ACLRole
	ACLRolePolicyLink                   = api.ACLRolePolicyLink
	ACLServiceIdentity                  = api.ACLServiceIdentity
	ACLTemplatedPolicy                  = api.ACLTemplatedPolicy
	ACLTemplatedPolicyResponse          = api.ACLTemplatedPolicyResponse
	ACLTemplatedPolicyVariables         = api.ACLTemplatedPolicyVariables
	ACLToken                            = api.ACLToken
	ACLTokenExpanded                    = api.ACLTokenExpanded
	ACLTokenFilterOptions               = api.ACLTokenFilterOptions
	ACLTokenListEntry                   = api.ACLTokenListEntry
	ACLTokenPolicyLink                  = api.ACLTokenPolicyLink
	ACLTokenRoleLink                    = api.ACLTokenRoleLink
	APIGatewayConfigEntry               = api.APIGatewayConfigEntry
	APIGatewayJWTClaimVerification      = api.APIGatewayJWTClaimVerification
	APIGatewayJWTProvider               = api.APIGatewayJWTProvider
	APIGatewayJWTRequirement            = api.APIGatewayJWTRequirement
	APIGatewayListener                  = api.APIGatewayListener
	APIGatewayPolicy                    = api.APIGatewayPolicy
	APIGatewayTLSConfiguration          = api.APIGatewayTLSConfiguration
	AccessLogsConfig                    = api.AccessLogsConfig
	Agent                               = api.Agent
	AgentAuthorize                      = api.AgentAuthorize
	AgentAuthorizeParams                = api.AgentAuthorizeParams
	AgentCheck                          = api.AgentCheck
	AgentCheckRegistration              = api.AgentCheckRegistration
	AgentMember                         = api.AgentMember
	AgentService                        = api.AgentService
	AgentServiceCheck                   = api.AgentServiceCheck
	AgentServiceChecks                  = api.AgentServiceChecks
	AgentServiceChecksInfo              = api.AgentServiceChecksInfo
	AgentServiceConnect                 = api.AgentServiceConnect
	AgentServiceConnectProxyConfig      = api.AgentServiceConnectProxyConfig
	AgentServiceRegistration            = api.AgentServiceRegistration
	AgentToken                          = api.AgentToken
	AgentWeights                        = api.AgentWeights
	Area                                = api.Area
	AreaJoinResponse                    = api.AreaJoinResponse
	AssignServiceManualVIPsRequest      = api.AssignServiceManualVIPsRequest
	AssignServiceManualVIPsResponse     = api.AssignServiceManualVIPsResponse
	AuditHashRequest                    = api.AuditHashRequest
	AuditHashResponse                   = api.AuditHashResponse
	AutopilotConfiguration              = api.AutopilotConfiguration
	AutopilotServer                     = api.AutopilotServer
	AutopilotServerStatus               = api.AutopilotServerStatus
	AutopilotServerType                 = api.AutopilotServerType
	AutopilotState                      = api.AutopilotState
	AutopilotUpgrade                    = api.AutopilotUpgrade
	AutopilotUpgradeStatus              = api.AutopilotUpgradeStatus
	AutopilotZone                       = api.AutopilotZone
	AutopilotZoneUpgradeVersions        = api.AutopilotZoneUpgradeVersions
	BindingRuleBindType                 = api.BindingRuleBindType
	BootstrapRequest                    = api.BootstrapRequest
	CAConfig                            = api.CAConfig
	CARoot                              = api.CARoot
	CARootList                          = api.CARootList
	Catalog                             = api.Catalog
	CatalogDeregistration               = api.CatalogDeregistration
	CatalogNode                         = api.CatalogNode
	CatalogNodeServiceList              = api.CatalogNodeServiceList
	CatalogRegistration                 = api.CatalogRegistration
	CatalogService                      = api.CatalogService
	CheckOp                             = api.CheckOp
	CheckTxnOp                          = api.CheckTxnOp
	Client                              = api.Client
	ClusterDiscoveryType                = api.ClusterDiscoveryType
	CommonCAProviderConfig              = api.CommonCAProviderConfig
	CompiledDiscoveryChain              = api.CompiledDiscoveryChain
	CompoundServiceName                 = api.CompoundServiceName
	Condition                           = api.Condition
	ConditionStatus                     = api.ConditionStatus
	Config                              = api.Config
	ConfigEntries                       = api.ConfigEntries
	ConfigEntry                         = api.ConfigEntry
	ConfigEntryStatus                   = api.ConfigEntryStatus
	Connect                             = api.Connect
	ConnectProxyConfig                  = api.ConnectProxyConfig
	ConsulCAProviderConfig              = api.ConsulCAProviderConfig
	CookieConfig                        = api.CookieConfig
	Coordinate                          = api.Coordinate
	CoordinateDatacenterMap             = api.CoordinateDatacenterMap
	CoordinateEntry                     = api.CoordinateEntry
	Debug                               = api.Debug
	DestinationConfig                   = api.DestinationConfig
	DiscoveryChain                      = api.DiscoveryChain
	DiscoveryChainOptions               = api.DiscoveryChainOptions
	DiscoveryChainResponse              = api.DiscoveryChainResponse
	DiscoveryFailover                   = api.DiscoveryFailover
	DiscoveryGraphNode                  = api.DiscoveryGraphNode
	DiscoveryResolver                   = api.DiscoveryResolver
	DiscoveryRoute                      = api.DiscoveryRoute
	DiscoverySplit                      = api.DiscoverySplit
	DiscoveryTarget                     = api.DiscoveryTarget
	EnvoyExtension                      = api.EnvoyExtension
	Event                               = api.Event
	ExportedService                     = api.ExportedService
	ExportedServicesConfigEntry         = api.ExportedServicesConfigEntry
	ExposeConfig                        = api.ExposeConfig
	ExposePath                          = api.ExposePath
	FileSystemCertificateConfigEntry    = api.FileSystemCertificateConfigEntry
	ForceLeaveOpts                      = api.ForceLeaveOpts
	GatewayConditionReason              = api.GatewayConditionReason
	GatewayConditionType                = api.GatewayConditionType
	GatewayService                      = api.GatewayService
	GatewayServiceTLSConfig             = api.GatewayServiceTLSConfig
	GatewayTLSConfig                    = api.GatewayTLSConfig
	GatewayTLSSDSConfig                 = api.GatewayTLSSDSConfig
	GaugeValue                          = api.GaugeValue
	HTTPFilters                         = api.HTTPFilters
	HTTPHeaderFilter                    = api.HTTPHeaderFilter
	HTTPHeaderMatch                     = api.HTTPHeaderMatch
	HTTPHeaderMatchType                 = api.HTTPHeaderMatchType
	HTTPHeaderModifiers                 = api.HTTPHeaderModifiers
	HTTPMatch                           = api.HTTPMatch
	HTTPMatchMethod                     = api.HTTPMatchMethod
	HTTPPathMatch                       = api.HTTPPathMatch
	HTTPPathMatchType                   = api.HTTPPathMatchType
	HTTPQueryMatch                      = api.HTTPQueryMatch
	HTTPQueryMatchType                  = api.HTTPQueryMatchType
	HTTPResponseFilters                 = api.HTTPResponseFilters
	HTTPRouteConfigEntry                = api.HTTPRouteConfigEntry
	HTTPRouteRule                       = api.HTTPRouteRule
	HTTPService                         = api.HTTPService
	HashPolicy                          = api.HashPolicy
	Health                              = api.Health
	HealthCheck                         = api.HealthCheck
	HealthCheckDefinition               = api.HealthCheckDefinition
	HealthChecks                        = api.HealthChecks
	HttpBasicAuth                       = api.HttpBasicAuth
	IngressGatewayConfigEntry           = api.IngressGatewayConfigEntry
	IngressListener                     = api.IngressListener
	IngressService                      = api.IngressService
	IngressServiceConfig                = api.IngressServiceConfig
	InlineCertificateConfigEntry        = api.InlineCertificateConfigEntry
	InstanceLevelRateLimits             = api.InstanceLevelRateLimits
	InstanceLevelRouteRateLimits        = api.InstanceLevelRouteRateLimits
	Intention                           = api.Intention
	IntentionAction                     = api.IntentionAction
	IntentionCheck                      = api.IntentionCheck
	IntentionHTTPHeaderPermission       = api.IntentionHTTPHeaderPermission
	IntentionHTTPPermission             = api.IntentionHTTPPermission
	IntentionJWTClaimVerification       = api.IntentionJWTClaimVerification
	IntentionJWTProvider                = api.IntentionJWTProvider
	IntentionJWTRequirement             = api.IntentionJWTRequirement
	IntentionMatch                      = api.IntentionMatch
	IntentionMatchType                  = api.IntentionMatchType
	IntentionPermission                 = api.IntentionPermission
	IntentionSourceType                 = api.IntentionSourceType
	Internal                            = api.Internal
	JSONWebKeySet                       = api.JSONWebKeySet
	JWKSCluster                         = api.JWKSCluster
	JWKSRetryPolicy                     = api.JWKSRetryPolicy
	JWKSTLSCertProviderInstance         = api.JWKSTLSCertProviderInstance
	JWKSTLSCertTrustedCA                = api.JWKSTLSCertTrustedCA
	JWKSTLSCertificate                  = api.JWKSTLSCertificate
	JWTCacheConfig                      = api.JWTCacheConfig
	JWTFilter                           = api.JWTFilter
	JWTForwardingConfig                 = api.JWTForwardingConfig
	JWTLocation                         = api.JWTLocation
	JWTLocationCookie                   = api.JWTLocationCookie
	JWTLocationHeader                   = api.JWTLocationHeader
	JWTLocationQueryParam               = api.JWTLocationQueryParam
	JWTProviderConfigEntry              = api.JWTProviderConfigEntry
	KV                                  = api.KV
	KVOp                                = api.KVOp
	KVPair                              = api.KVPair
	KVPairs                             = api.KVPairs
	KVTxnOp                             = api.KVTxnOp
	KVTxnOps                            = api.KVTxnOps
	KVTxnResponse                       = api.KVTxnResponse
	KeyringResponse                     = api.KeyringResponse
	KubernetesAuthMethodConfig          = api.KubernetesAuthMethodConfig
	LeafCert                            = api.LeafCert
	LeastRequestConfig                  = api.LeastRequestConfig
	License                             = api.License
	LicenseReply                        = api.LicenseReply
	LinkedService                       = api.LinkedService
	LoadBalancer                        = api.LoadBalancer
	LocalJWKS                           = api.LocalJWKS
	Locality                            = api.Locality
	Lock                                = api.Lock
	LockOptions                         = api.LockOptions
	LogSinkType                         = api.LogSinkType
	MemberACLMode                       = api.MemberACLMode
	MembersOpts                         = api.MembersOpts
	MeshConfigEntry                     = api.MeshConfigEntry
	MeshDirectionalHTTPConfig           = api.MeshDirectionalHTTPConfig
	MeshDirectionalTLSConfig            = api.MeshDirectionalTLSConfig
	MeshGatewayConfig                   = api.MeshGatewayConfig
	MeshGatewayMode                     = api.MeshGatewayMode
	MeshHTTPConfig                      = api.MeshHTTPConfig
	MeshTLSConfig                       = api.MeshTLSConfig
	MetricsInfo                         = api.MetricsInfo
	MutualTLSMode                       = api.MutualTLSMode
	Namespace                           = api.Namespace
	NamespaceACLConfig                  = api.NamespaceACLConfig
	Namespaces                          = api.Namespaces
	Node                                = api.Node
	NodeOp                              = api.NodeOp
	NodeTxnOp                           = api.NodeTxnOp
	OIDCAuthMethodConfig                = api.OIDCAuthMethodConfig
	Operator                            = api.Operator
	OperatorHealthReply                 = api.OperatorHealthReply
	Partition                           = api.Partition
	Partitions                          = api.Partitions
	PassiveHealthCheck                  = api.PassiveHealthCheck
	PeeredServiceName                   = api.PeeredServiceName
	Peering                             = api.Peering
	PeeringEstablishRequest             = api.PeeringEstablishRequest
	PeeringEstablishResponse            = api.PeeringEstablishResponse
	PeeringGenerateTokenRequest         = api.PeeringGenerateTokenRequest
	PeeringGenerateTokenResponse        = api.PeeringGenerateTokenResponse
	PeeringListRequest                  = api.PeeringListRequest
	PeeringMeshConfig                   = api.PeeringMeshConfig
	PeeringReadResponse                 = api.PeeringReadResponse
	PeeringRemoteInfo                   = api.PeeringRemoteInfo
	PeeringState                        = api.PeeringState
	PeeringStreamStatus                 = api.PeeringStreamStatus
	Peerings                            = api.Peerings
	PointValue                          = api.PointValue
	PreparedQuery                       = api.PreparedQuery
	PreparedQueryDefinition             = api.PreparedQueryDefinition
	PreparedQueryExecuteResponse        = api.PreparedQueryExecuteResponse
	ProxyConfigEntry                    = api.ProxyConfigEntry
	ProxyMode                           = api.ProxyMode
	QueryDNSOptions                     = api.QueryDNSOptions
	QueryDatacenterOptions              = api.QueryDatacenterOptions
	QueryFailoverOptions                = api.QueryFailoverOptions
	QueryFailoverTarget                 = api.QueryFailoverTarget
	QueryMeta                           = api.QueryMeta
	QueryOptions                        = api.QueryOptions
	QueryTemplate                       = api.QueryTemplate
	RaftConfiguration                   = api.RaftConfiguration
	RaftServer                          = api.RaftServer
	RateLimitIPConfigEntry              = api.RateLimitIPConfigEntry
	RateLimits                          = api.RateLimits
	Raw                                 = api.Raw
	ReadWriteRatesConfig                = api.ReadWriteRatesConfig
	ReadableDuration                    = api.ReadableDuration
	RemoteJWKS                          = api.RemoteJWKS
	RequestNormalizationMeshConfig      = api.RequestNormalizationMeshConfig
	ResolvedConsumers                   = api.ResolvedConsumers
	ResolvedExportedService             = api.ResolvedExportedService
	ResourceReference                   = api.ResourceReference
	RetryFilter                         = api.RetryFilter
	RetryPolicyBackOff                  = api.RetryPolicyBackOff
	RingHashConfig                      = api.RingHashConfig
	RouteConditionReason                = api.RouteConditionReason
	RouteConditionType                  = api.RouteConditionType
	SamenessGroupConfigEntry            = api.SamenessGroupConfigEntry
	SamenessGroupMember                 = api.SamenessGroupMember
	SampledValue                        = api.SampledValue
	Semaphore                           = api.Semaphore
	SemaphoreOptions                    = api.SemaphoreOptions
	SerfMember                          = api.SerfMember
	ServerHealth                        = api.ServerHealth
	ServiceAddress                      = api.ServiceAddress
	ServiceCheck                        = api.ServiceCheck
	ServiceConfigEntry                  = api.ServiceConfigEntry
	ServiceConsumer                     = api.ServiceConsumer
	ServiceEntry                        = api.ServiceEntry
	ServiceIntentionsConfigEntry        = api.ServiceIntentionsConfigEntry
	ServiceKind                         = api.ServiceKind
	ServiceOp                           = api.ServiceOp
	ServiceQuery                        = api.ServiceQuery
	ServiceRegisterOpts                 = api.ServiceRegisterOpts
	ServiceResolverConfigEntry          = api.ServiceResolverConfigEntry
	ServiceResolverFailover             = api.ServiceResolverFailover
	ServiceResolverFailoverPolicy       = api.ServiceResolverFailoverPolicy
	ServiceResolverFailoverTarget       = api.ServiceResolverFailoverTarget
	ServiceResolverPrioritizeByLocality = api.ServiceResolverPrioritizeByLocality
	ServiceResolverRedirect             = api.ServiceResolverRedirect
	ServiceResolverSubset               = api.ServiceResolverSubset
	ServiceRoute                        = api.ServiceRoute
	ServiceRouteDestination             = api.ServiceRouteDestination
	ServiceRouteHTTPMatch               = api.ServiceRouteHTTPMatch
	ServiceRouteHTTPMatchHeader         = api.ServiceRouteHTTPMatchHeader
	ServiceRouteHTTPMatchQueryParam     = api.ServiceRouteHTTPMatchQueryParam
	ServiceRouteMatch                   = api.ServiceRouteMatch
	ServiceRouterConfigEntry            = api.ServiceRouterConfigEntry
	ServiceSplit                        = api.ServiceSplit
	ServiceSplitterConfigEntry          = api.ServiceSplitterConfigEntry
	ServiceTxnOp                        = api.ServiceTxnOp
	ServiceUsage                        = api.ServiceUsage
	Session                             = api.Session
	SessionEntry                        = api.SessionEntry
	SessionOp                           = api.SessionOp
	SessionTxnOp                        = api.SessionTxnOp
	Snapshot                            = api.Snapshot
	SourceIntention                     = api.SourceIntention
	Status                              = api.Status
	StatusError                         = api.StatusError
	TCPRouteConfigEntry                 = api.TCPRouteConfigEntry
	TCPService                          = api.TCPService
	TLSConfig                           = api.TLSConfig
	TerminatingGatewayConfigEntry       = api.TerminatingGatewayConfigEntry
	TimeoutFilter                       = api.TimeoutFilter
	TransferLeaderResponse              = api.TransferLeaderResponse
	TransparentProxyConfig              = api.TransparentProxyConfig
	TransparentProxyMeshConfig          = api.TransparentProxyMeshConfig
	Txn                                 = api.Txn
	TxnError                            = api.TxnError
	TxnErrors                           = api.TxnErrors
	TxnOp                               = api.TxnOp
	TxnOps                              = api.TxnOps
	TxnResponse                         = api.TxnResponse
	TxnResult                           = api.TxnResult
	TxnResults                          = api.TxnResults
	URLRewrite                          = api.URLRewrite
	Upstream                            = api.Upstream
	UpstreamConfig                      = api.UpstreamConfig
	UpstreamConfiguration               = api.UpstreamConfiguration
	UpstreamDestType                    = api.UpstreamDestType
	UpstreamLimits                      = api.UpstreamLimits
	Usage                               = api.Usage
	UserEvent                           = api.UserEvent
	Weights                             = api.Weights
	WriteMeta                           = api.WriteMeta
	WriteOptions                        = api.WriteOptions
)

func DecodeConfigEntry(raw map[string]interface{}) (api.ConfigEntry, error) {
	return api.DecodeConfigEntry(raw)
}

func DecodeConfigEntryFromJSON(data []byte) (api.ConfigEntry, error) {
	return api.DecodeConfigEntryFromJSON(data)
}

func DefaultConfig() *api.Config {
	return api.DefaultConfig()
}

func DefaultConfigWithLogger(logger hclog.Logger) *api.Config {
	return api.DefaultConfigWithLogger(logger)
}

func DefaultNonPooledConfig() *api.Config {
	return api.DefaultNonPooledConfig()
}

func IsRetryableError(err error) bool {
	return api.IsRetryableError(err)
}

func MakeConfigEntry(kind, name string) (api.ConfigEntry, error) {
	return api.MakeConfigEntry(kind, name)
}

func NewAutopilotConfiguration() api.AutopilotConfiguration {
	return api.NewAutopilotConfiguration()
}

func NewClient(config *api.Config) (*api.Client, error) {
	return api.NewClient(config)
}

func NewHttpClient(transport *http.Transport, tlsConf api.TLSConfig) (*http.Client, error) {
	return api.NewHttpClient(transport, tlsConf)
}

func NewReadableDuration(dur time.Duration) *api.ReadableDuration {
	return api.NewReadableDuration(dur)
}

func ParseConsulCAConfig(raw map[string]interface{}) (*api.ConsulCAProviderConfig, error) {
	return api.ParseConsulCAConfig(raw)
}

func ParseKubernetesAuthMethodConfig(raw map[string]interface{}) (*api.KubernetesAuthMethodConfig, error) {
	return api.ParseKubernetesAuthMethodConfig(raw)
}

func ParseServiceAddr(addrPort string) (api.ServiceAddress, error) {
	return api.ParseServiceAddr(addrPort)
}

func SetupTLSConfig(tlsConfig *api.TLSConfig) (*tls.Config, error) {
	return api.SetupTLSConfig(tlsConfig)
}

func ValidateGatewayConditionReason(name api.GatewayConditionType, status api.ConditionStatus, reason api.GatewayConditionReason) error {
	return api.ValidateGatewayConditionReason(name, status, reason)
}

func ValidateRouteConditionReason(name api.RouteConditionType, status api.ConditionStatus, reason api.RouteConditionReason) error {
	return api.ValidateRouteConditionReason(name, status, reason)
}
