// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from consul.go.

// Package consul contains generated code by adptool.
package consul

import (
	"time"

	consul "github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/hashicorp/consul/api"
)

const (
	MultiDatacenter  = consul.MultiDatacenter
	SingleDatacenter = consul.SingleDatacenter
)

type (
	Client          = consul.Client
	Config          = consul.Config
	Datacenter      = consul.Datacenter
	Option          = consul.Option
	Registry        = consul.Registry
	ServiceResolver = consul.ServiceResolver
)

func New(apiClient *api.Client, opts ...consul.Option) *consul.Registry {
	return consul.New(apiClient, opts...)
}

func WithDatacenter(dc consul.Datacenter) consul.Option {
	return consul.WithDatacenter(dc)
}

func WithDeregisterCriticalServiceAfter(interval int) consul.Option {
	return consul.WithDeregisterCriticalServiceAfter(interval)
}

func WithHealthCheck(enable bool) consul.Option {
	return consul.WithHealthCheck(enable)
}

func WithHealthCheckInterval(interval int) consul.Option {
	return consul.WithHealthCheckInterval(interval)
}

func WithHeartbeat(enable bool) consul.Option {
	return consul.WithHeartbeat(enable)
}

func WithServiceCheck(checks ...*api.AgentServiceCheck) consul.Option {
	return consul.WithServiceCheck(checks...)
}

func WithServiceResolver(fn consul.ServiceResolver) consul.Option {
	return consul.WithServiceResolver(fn)
}

func WithTags(tags []string) consul.Option {
	return consul.WithTags(tags)
}

func WithTimeout(timeout time.Duration) consul.Option {
	return consul.WithTimeout(timeout)
}
